// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1753968649);
user_pref("app.update.lastUpdateTime.background-update-timer", 1753970919);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1753968649);
user_pref("app.update.migrated.updateDir3.DBF427A430B95848", true);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.keyURL", "http://localhost/safebrowsing-dummy/newkey");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.selfsupport.url", "https://localhost/selfrepair");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("datareporting.policy.firstRunURL", "");
user_pref("devtools.browserconsole.contentMessages", true);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.command-button-noautohide.enabled", true);
user_pref("devtools.console.stdout.chrome", true);
user_pref("devtools.debugger.prompt-connection", false);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.debugger.remote-websocket", true);
user_pref("devtools.errorconsole.enabled", true);
user_pref("devtools.everOpened", true);
user_pref("devtools.inspector.activeSidebar", "ruleview");
user_pref("devtools.inspector.selectedSidebar", "ruleview");
user_pref("devtools.inspector.showAllAnonymousContent", true);
user_pref("devtools.inspector.showUserAgentStyles", true);
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppBuildId", "20250724162348");
user_pref("extensions.lastAppVersion", "7.1-beta.48+735922a2b");
user_pref("extensions.lastPlatformVersion", "128.9.0");
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.firstRunGuidance", false);
user_pref("extensions.zotero.httpServer.localAPI.enabled", true);
user_pref("extensions.zotero.httpServer.port", 23124);
user_pref("extensions.zotero.reportTranslationFailure", false);
user_pref("extensions.zoteroMacWordIntegration.installed", true);
user_pref("extensions.zoteroMacWordIntegration.skipInstallation", true);
user_pref("extensions.zoteroOpenOfficeIntegration.skipInstallation", true);
user_pref("extensions.zoteroWinWordIntegration.skipInstallation", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20250327044906");
user_pref("gfx-shader-check.device-id", "0x9a49");
user_pref("gfx-shader-check.driver-version", "32.0.101.6129");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("idle.lastDailyNotification", 1753884285);
user_pref("media.hardware-video-decoding.failed", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1753884285186");
user_pref("sanity-test.device-id", "0x9a49");
user_pref("sanity-test.driver-version", "32.0.101.6129");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20250327044906");
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1753884285);
user_pref("toolkit.startup.max_resumed_crashes", -1);
user_pref("urlclassifier.updateinterval", 172800);
