// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1753968647);
user_pref("app.update.lastUpdateTime.background-update-timer", 1753970916);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1753968647);
user_pref("app.update.migrated.updateDir3.DBF427A430B95848", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.keyURL", "http://localhost/safebrowsing-dummy/newkey");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.selfsupport.url", "https://localhost/selfrepair");
user_pref("browser.startup.homepage", "about:blank");
user_pref("datareporting.policy.firstRunURL", "");
user_pref("devtools.browserconsole.contentMessages", true);
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.prompt-connection", false);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.debugger.remote-websocket", true);
user_pref("devtools.errorconsole.enabled", true);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppBuildId", "20250724162348");
user_pref("extensions.lastAppVersion", "7.1-beta.48+735922a2b");
user_pref("extensions.lastPlatformVersion", "128.9.0");
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.webextensions.uuids", "{\"Format@euclpts.com\":\"838a4b75-aad7-4bd8-bdc9-8751a5df3772\",\"Normalize@euclpts.com\":\"ac2e523e-c181-4949-9718-64d9105c7174\"}");
user_pref("extensions.zotero.dataDir", "C:\\Users\\57497\\Zotero");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.firstRunGuidance", false);
user_pref("extensions.zotero.httpServer.localAPI.enabled", true);
user_pref("extensions.zotero.httpServer.port", 23124);
user_pref("extensions.zotero.lastViewedFolder", "C189");
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"true\"},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"337\",\"height\":\"205\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-splitter-stacked\":{\"state\":\"collapsed\"}}");
user_pref("extensions.zotero.panes.Format\\@euclpts\\.com-example.open", true);
user_pref("extensions.zotero.panes.Format\\@euclpts\\.com-reader-example.open", true);
user_pref("extensions.zotero.panes.Normalize\\@euclpts\\.com-example.open", true);
user_pref("extensions.zotero.panes.Normalize\\@euclpts\\.com-reader-example.open", true);
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 15);
user_pref("extensions.zotero.purge.creators", true);
user_pref("extensions.zotero.purge.tags", true);
user_pref("extensions.zotero.reportTranslationFailure", false);
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"C22\":true,\"P1\":false,\"L2\":true,\"L3\":true,\"L4\":true,\"L5\":true,\"L6\":true,\"C172\":true}");
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1753949976);
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroMacWordIntegration.installed", true);
user_pref("extensions.zoteroMacWordIntegration.skipInstallation", true);
user_pref("extensions.zoteroOpenOfficeIntegration.skipInstallation", true);
user_pref("extensions.zoteroWinWordIntegration.skipInstallation", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20250327044906");
user_pref("gfx-shader-check.device-id", "0x9a49");
user_pref("gfx-shader-check.driver-version", "32.0.101.6129");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("idle.lastDailyNotification", 1753884285);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1753884285217");
user_pref("sanity-test.device-id", "0x9a49");
user_pref("sanity-test.driver-version", "32.0.101.6129");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20250327044906");
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1753884285);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Keyboard presence confirmed.");
user_pref("urlclassifier.updateinterval", 172800);
